### ISSUE TITLE
 Split long links (first trial max. 300m)

### ISSUE THREAD

**Issue by EmnaBH** [EPajares/goat#119]

**Comment by EmnaBH** [comment]
Split long links (max. 300 m) that don't exclude:
- class_id_walking
- categorie_foot

**Comment by EPajares** [comment]
I changed strategy as the Python scripts was too slow. I moved everything to SQL and Pl/Pgsql. Everything is inside the data_prepartion/SQL/network_prepartion.sql under the $$DO-block. The calculation time is reduced now to some seconds.
