### ISSUE TITLE
Add important attributes to the table 'ways'

### ISSUE THREAD

**Issue by EmnaBH** [EPajares/goat#120]
Attributes: sidewalk, cycleway, busway, tags,  bicycle_road, surface

**Comment by EmnaBH** [comment]
I added two new columns (surface and tags) to the table ways. These columns contain the matching values from the table planet_osm_line.

**Comment by UJehle** [comment]
I added the following columns to the table ways: 
highway, incline, lanes, lit, parking, segregated, sidewalk, sidewalk_both_width, sidewalk_left_width, sidewalk_right_width, smoothness, wheelchair, width
