### ISSUE TITLE
Can't install dos2unix

### ISSUE THREAD

**Issue by MoritzSGit** [EPajares/goat#132]
When you do the setup procedure on Windows machines, you need to convert the install scripts from dos to unix line endings. 
Therefore the documentation instructs you to download the package dos2unix on your virtual machine.
However, the package manager cannot find the package. To find the packages, you first need to run `sudo apt-get update`.
I suggest to either add this step to the documentation, or to automatically run the command on first start of the virtual machine.

**Comment by EPajares** [comment]
I added "sudo apt update" to the VAGRANTFILE. No it should be possible to install any package after starting the VM.
