### ISSUE TITLE
User interface: highlight selected option

### ISSUE THREAD

**Issue by UJehle** [EPajares/goat#144]
I think it would be useful, if the selected option (set a starting point, load network, add a new link) is highlighted in the menu. Maybe in another shade of green or by inversing the colours.

**Comment by EPajares** [comment]
Good idea! This is tackled in the development of the new front-end. By the end of this month or at the beginning of October it should be online. If you want you can already test it though. It is in the development branch inside the folder app/client. You need to run npm install and afterwards npm run serve. The testing server is listening on port 5000.
