### ISSUE TITLE
Change turqoise color that highlights buttons

### ISSUE THREAD

**Issue by EPajares** [EPajares/goat#150]
![Auswahl_045](https://user-images.githubusercontent.com/42171996/65536226-49595d00-df03-11e9-8e8c-37972ba209ad.png)

This color is not really visible on many screen. Can we search an alternative?

@majkshkurti

**Comment by majkshkurti** [comment]
I undestand. 
Can you test out some colors, and suggest me what we could use ?

**Comment by EPajares** [comment]
I will test it and let you know!
