### ISSUE TITLE
Restructure variable categories for wheelchair and lit visualization/routing

### ISSUE THREAD

**Issue by UJehle** [EPajares/goat#206]
- Move the variable categories from the variable_container to extra tables (e.g. "wheelchair_settings", "lit_settings")
- Update SQL views in Geoserver
- Adapt the function select_from_variable_container or create a new function

**Comment by EPajares** [comment]
I think for the wheelchair_setting and lit_setting we can create an object_type in the variable container. This could save us some lines of code. But this is forcing us to use the jsonb-format, which is bit more harder to handle.

**Comment by EPajares** [comment]
We can then probably also avoid to adjust the function select_from_variable_container

**Comment by EPajares** [comment]
How to use jsonb: http://www.postgresqltutorial.com/postgresql-json/
