### ISSUE TITLE
Improve Gravity-based indicator

### ISSUE THREAD

**Issue by EPajares** [EPajares/goat#92]
- [x] Test different impedance parameters
- [x] Flexible calculation heatmap
- [x] Integration front-end
- [x] Test chart libraries front-end for different impedance functions
- [ ] Allow for dynamic recalculation

**Comment by testingEliasPajares** [comment]
this is a test

**Comment by EPajares** [comment]
We will change the strategy in the backend, as performance for the dynamic re-calculation was to bad. We will pre-calculate the index for the following sensitivity parameters:

**Comment by EPajares** [comment]
I will add a new issue for dynamic recalculation
